name = "quantum-skies"
author = "jmoiron"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d72ae02c01b1c825e2d8f68dcf4a3a4baa5731cb69b7b3c1d2a08b12e61bad13"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
