name = "quantum-skies"
author = "jmoiron"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d38882d3468a5e7527174b5b4d9d6632cf14ad178ce3cfc669cb5ad346bded4"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
