name = "Quantum Skies"
author = "jmoiron"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cefc9d5ca3a3be07ab9e37d3f0648da75af848b19f5125883de18fc61d960787"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
